spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/vote?useTimezone=true&serverTimezone=UTC
    username: vote
    password: vote
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    ddl-auto: none
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        show_sql: true
  sql:
    init:
      platform: mariadb
  batch:
    jdbc:
      isolation-level-for-create:
springdoc:
  paths-to-match: /api/vote/**, /api/ruling/**
  swagger-ui:
    use-root-path: true